name: kyle-example-action
description: An example Action
author: Kyle Colantonio

branding:
  icon: aperture
  color: blue

inputs:
  format:
    description: The date format to output in
    required: false
    default: "+%Y-%m-%dT%H:%M:%S"

outputs:
  date:
    description: The date in the format provided
    value: ${{ steps.date.outputs.date-output }}

runs:
  using: composite
  steps:
    - name: Get Date & Time
      id: date
      shell: bash
      run: |
        DATE_OUTPUT=$(date '${{ inputs.format }}')
        echo "$DATE_OUTPUT"
        echo "date-output=$DATE_OUTPUT" >> "$GITHUB_OUTPUT"
